# Generated by Django 4.2.19 on 2025-02-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WordAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_word', models.CharField(max_length=50)),
                ('word_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.wordlevel')),
            ],
        ),
    ]
